### ISSUE TITLE
Enhance convert_data.py

### ISSUE THREAD

**Issue by xdshang** [li-s/Handwriting-recognition#2]
1. Rename "test"s in `convert_data.py` and `training.py` to "val" (validation);
2. Add option in `convert_train` to switch on returning all the training samples, which means validation samples are part of training samples. This feature allows your model to learn from the whole training data.

**Comment by li-s** [comment]
1. Fixed @8cb3251efc17721ae84344acb1a97d2cc80c96a3
2. Fixed @6d13b303ba7154e3e52c5efd59f2974984bdccd5
